use_frameworks!

target 'Salon' do
    pod 'UITextField+Shake'
    pod 'Eureka'
    pod 'ESTabBarController-swift'
	pod 'Kingfisher'
	pod 'Alamofire'
  	pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Functions'
    pod 'Firebase/Messaging'
    pod 'Firebase/Firestore'
    pod 'GoogleSignIn'
    pod 'SwiftyUserDefaults'
    pod 'SwiftyJSON'
    pod 'SwiftFormat/CLI'
    pod 'SnapKit'
    pod 'WhatsNewKit'
    pod 'Stripe'
    pod 'FBSDKLoginKit'
    pod 'ImageSlideshow', '~> 1.6'
    pod 'DateTimePicker'
    pod 'McPicker', '~> 2.0.0'
    pod 'Cosmos'
    pod 'Fabric', '~> 1.10.2'
    pod 'Crashlytics', '~> 3.13.3'
    pod 'SDWebImage'
#    pod 'FirebaseUI/Storage'
end
